package lumina.components.styles

class Transition {
    companion object {
		val ALL = "all"
		val BACKGROUND = "background"
		val BACKGROUNDCOLOR = "background-color"
		val BORDER = "border"
		val BORDERCOLOR = "border-color"
		val BORDERRADIUS = "border-radius"
		val BORDERSPACING = "border-spacing"
		val BORDERWIDTH = "border-width"
		val BOTTOM = "bottom"
		val BOXSHADOW = "box-shadow"
		val CLIP = "clip"
		val COLOR = "color"
		val CONTENT = "content"
		val CURSOR = "cursor"
		val FILTER = "filter"
		val FLEX = "flex"
		val FONT = "font"
		val FONTFAMILY = "font-family"
		val FONTSIZE = "font-size"
		val FONTSTYLE = "font-style"
		val FONTVARIANT = "font-variant"
		val FONTWEIGHT = "font-weight"
		val HEIGHT = "height"
		val LEFT = "left"
		val LETTERSPACING = "letter-spacing"
		val LINEHEIGHT = "line-height"
		val MARGIN = "margin"
		val MARGINBOTTOM = "margin-bottom"
		val MARGINLEFT = "margin-left"
		val MARGINRIGHT = "margin-right"
		val MARGINTOP = "margin-top"
		val MAXHEIGHT = "max-height"
		val MAXWIDTH = "max-width"
		val OPACITY = "opacity"
		val OUTLINE = "outline"
		val OUTLINECOLOR = "outline-color"
		val OUTLINEOFFSET = "outline-offset"
		val OUTLINESTYLE = "outline-style"
		val OUTLINEWIDTH = "outline-width"
		val OVERFLOW = "overflow"
		val PADDING = "padding"
		val PADDINGBOTTOM = "padding-bottom"
		val PADDINGLEFT = "padding-left"
		val PADDINGRIGHT = "padding-right"
		val PADDINGTOP = "padding-top"
		val PERSPECTIVE = "perspective"
		val RIGHT = "right"
		val TEXTDECORATION = "text-decoration"
		val TEXTDECORATIONCOLOR = "text-decoration-color"
		val TEXTINDENT = "text-indent"
		val TEXTSHADOW = "text-shadow"
		val TEXTTRANSFORM = "text-transform"
		val TOP = "top"
		val TRANSFORM = "transform"
		val TRANSFORMORIGIN = "transform-origin"
		val TRANSITION = "transition"
		val VERTICALALIGN = "vertical-align"
		val VISIBILITY = "visibility"
		val WIDTH = "width"
		val WORDSPACING = "word-spacing"
		val ZINDEX = "z-index"
    }
}
            